### ISSUE TITLE
Camera not working properly

### ISSUE THREAD

**Issue by Lorenzogasparini1975** [readyplayerme/rpm-unity-sdk-webview#17]
Hi,
when I try to take a photo to create my avatar using webview the camera freezes, if I don't touch the screen. The only way to unfreeze it is to touch the screen.

 - Ready Player Me Core 1.3.2
 - Ready Player Me Avatar Loader 1.3.3
 - Ready Player Me WebView 1.2.0
 - glTFast 5.0.0
 - Unity Editor version 2021.3.22f1
 - Render Pipeline and version 12.1.10
 - Operating System Windows 11
 - Platform: Android

 - Device: Samsung A20e
 - OS: Android 11

**Comment by HarrisonHough** [comment]
Hey there! 
Apologies for the delay. 
Have you tried updating to the latest version of the sdk? 
We are unable to replicate on our end on the latest version.
