### ISSUE TITLE
World space canvas rendering in VR Meta Quest2?

### ISSUE THREAD

**Issue by Sharma1331** [readyplayerme/rpm-unity-sdk-webview#27]
Hi

Is WebView support VR Meta Quest2? if Yes so how we can render webview in world space canvas in Unity?

**Comment by HarrisonHough** [comment]
This webview uses native android UI and does not support world space canvas. 
There are currently no plans to add support for this. For VR (and world space canvas) we recommend trying our Avatar Creator that is included in Ready Player Me Core package. It uses native unity UI and supports world space canvas's. 
You can find documentation for this in our documentation 
https://docs.readyplayer.me/ready-player-me/integration-guides/unity/avatar-creator/engine-native-avatar-creator
