### ISSUE TITLE
WebView Crashes 

### ISSUE THREAD

**Issue by Lorenzogasparini1975** [readyplayerme/rpm-unity-sdk-webview#9]
Hi,
when I run the WebView in my Android device and try to upload a photo from the file system the app crashes immediately without any errors. I found this problem also in the preview versions of RPM but I wasn't able to solve it. 
Usually the app crashes right after I choose the image.
Do you know what the problem is and how to solve it?

This is the screenshot:
![Screenshot_20230321-154241_ReadyPlayerMe20](https://user-images.githubusercontent.com/79420481/226644934-033302e8-95f7-4507-89d1-a1cbd5bf2e5d.jpg)

 - Ready Player Me Core version: 1.1.0
 - Ready Player Me Avatar Loader: 1.1.0
 - Ready Player Me WebView version: 1.1.0
 - glTFast version; 5.0.0
 - Unity Editor version 2021.3.6f1
 - Operating System: Windows 11
 - Platform: Android
 - Device: SamsungA20e
 - OS: Android 11

Thanks, Lorenzo

**Comment by srcnalt** [comment]
Hi Lorenzo,

Could you import Android LogCat package through Unity Package Manager, run the project while your phone is connected via cable, filter Unity processes only and share the error messages you get when the app crashes?

**Comment by Lorenzogasparini1975** [comment]
thank you for your answer.
Everytime the app crashes Android LogCat show me these errors:

![errors](https://user-images.githubusercontent.com/79420481/226689522-e3c164bd-faf4-4e80-ae6b-522a49e4269c.png)
![errors2](https://user-images.githubusercontent.com/79420481/226689340-0afae1af-7a3e-429b-bb26-b15302bd3aeb.png)
![errors3](https://user-images.githubusercontent.com/79420481/226689381-c96bf136-e515-411a-b60e-131c7dc0b30b.png)

I hope this can help...

**Comment by DanDevChen** [comment]
Hi, I have the same problem. Any solution?

**Comment by Lorenzogasparini1975** [comment]
Hi,
Not yet

> Hi, I have the same problem. Any solution?

**Comment by DanDevChen** [comment]
Sorry for the rush, but I would need use a solution because I have to submit the project in a few days, can you help me please?

**Comment by DanDevChen** [comment]
> Hi Lorenzo,
> 
> Could you import Android LogCat package through Unity Package Manager, run the project while your phone is connected via cable, filter Unity processes only and share the error messages you get when the app crashes?

Hi, did I upload the information correctly?

**Comment by srcnalt** [comment]
@Lorenzogasparini1975 could you test this building in another version of Unity, I can't replicate this but found a similar issue being reported some while ago which happened in the same version of unity.

**Comment by Lorenzogasparini1975** [comment]
Thank you, it seems to be working, I will do further testing, but so far I have not encountered any more crashes.
